version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ../Diplom/Dockerfile
    depends_on:
      - psql-db
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/myProject
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_REDIS_HOST=redis

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  psql-db:
    image: postgres:16.0
    container_name: psql-db
    environment:
      POSTGRES_DB: "myProject"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      -  5432:5432


  redis:
    image: redis:7.0.12
    ports:
      - 6379:6379