spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://psql-db:5432/myProject
    username: postgres
    password: admin
    hikari:
      schema: myproject_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS myproject_schema
      connection-timeout: 10000

  docker:
    compose:
      enabled: true


app:
  upload:
    path: "content"
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 300m
